# Generated by Django 4.2.30 on 2026-07-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', '승인 대기'), ('approved', '승인됨'), ('rejected', '반려됨'), ('cancelled', '취소됨')], default='requested', max_length=20, verbose_name='상태')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='수강 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='수강 종료일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='반려 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='강의')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '수강 신청',
                'verbose_name_plural': '수강 신청',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'course', 'status'], name='enrollments_user_id_2335bf_idx'), models.Index(fields=['status', 'start_date', 'end_date'], name='enrollments_status_db5522_idx')],
            },
        ),
    ]
