# Generated by Django 4.2.30 on 2026-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수료일시'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_note',
            field=models.TextField(blank=True, verbose_name='수료 메모'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_progress_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='수료 판정 진도율'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='수료 여부'),
        ),
    ]
