# Generated by Django 4.2.30 on 2026-07-07 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_certificate_enabled_course_require_quiz_pass_and_more'),
        ('enrollments', '0002_enrollment_completed_at_enrollment_completion_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='신청 사유')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('extension_start_date', models.DateField(blank=True, null=True, verbose_name='연장 시작일')),
                ('extension_end_date', models.DateField(blank=True, null=True, verbose_name='연장 종료일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollment_requests', to='courses.course', verbose_name='강의')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollment_requests', to='enrollments.enrollment', verbose_name='기존 수강')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reenrollment_requests', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reenrollment_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '재수강 신청',
                'verbose_name_plural': '재수강 신청',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'course', 'status'], name='enrollments_user_id_02ece7_idx'), models.Index(fields=['status', 'requested_at'], name='enrollments_status_f0ccfc_idx'), models.Index(fields=['processed_at'], name='enrollments_process_c2cf76_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reenrollmentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('enrollment',), name='unique_pending_reenrollment_per_enrollment'),
        ),
    ]
