# Generated by Django 4.2.30 on 2026-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_reenrollmentrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='expiry_notice_7d_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='7일 전 만료 알림 발송일시'),
        ),
    ]
