# Generated by Django 4.2.30 on 2026-07-15 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollment_expiry_notice_7d_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enrollment_request', '수강 신청 관리자 알림'), ('enrollment_approval', '수강 승인 수강생 알림'), ('enrollment_expiry_7d', '수강 종료 7일 전 알림')], max_length=40, verbose_name='메일 유형')),
                ('status', models.CharField(choices=[('sent', '발송 완료'), ('failed', '발송 실패'), ('skipped', '발송 생략')], max_length=20, verbose_name='상태')),
                ('recipient_email', models.CharField(blank=True, max_length=500, verbose_name='수신자')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='제목')),
                ('user_id_value', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='수강생 ID')),
                ('user_label', models.CharField(blank=True, max_length=160, verbose_name='수강생')),
                ('course_id_value', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='강의 ID')),
                ('course_title', models.CharField(blank=True, max_length=200, verbose_name='강의명')),
                ('error_message', models.TextField(blank=True, verbose_name='오류/처리 메모')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일시')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='enrollments.enrollment', verbose_name='수강')),
            ],
            options={
                'verbose_name': '메일 발송 로그',
                'verbose_name_plural': '메일 발송 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='enrollments_kind_614cbe_idx'), models.Index(fields=['status', '-created_at'], name='enrollments_status_36b2b7_idx'), models.Index(fields=['recipient_email', '-created_at'], name='enrollments_recipie_3c43b8_idx')],
            },
        ),
    ]
