# Generated by Django 4.2.30 on 2026-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_emaildeliverylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='status',
            field=models.CharField(choices=[('queued', '발송 대기'), ('sent', '발송 완료'), ('failed', '발송 실패'), ('skipped', '발송 생략')], max_length=20, verbose_name='상태'),
        ),
    ]
