# Generated by Django 4.2.30 on 2026-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_emaildeliverylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='kind',
            field=models.CharField(choices=[('enrollment_request', '수강 신청 관리자 알림'), ('enrollment_approval', '수강 승인 수강생 알림'), ('enrollment_expiry_7d', '수강 종료 7일 전 알림'), ('account_withdrawal_request', '계정 탈퇴 요청 관리자 알림')], max_length=40, verbose_name='메일 유형'),
        ),
    ]
