# Generated by Django 4.2.30 on 2026-07-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def sync_existing_payment_statuses(apps, schema_editor):
    Enrollment = apps.get_model('enrollments', 'Enrollment')
    Enrollment.objects.filter(course__pricing_type='free').update(payment_status='not_required')
    Enrollment.objects.filter(course__pricing_type='paid', status='requested').update(payment_status='pending')
    Enrollment.objects.filter(course__pricing_type='paid', status='approved').update(payment_status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0007_alter_emaildeliverylog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입금 확인일시'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmed_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='입금 확인 관리자'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name='입금 메모'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('not_required', '입금 불필요'), ('pending', '입금 대기'), ('confirmed', '입금 확인'), ('waived', '면제')], default='not_required', max_length=20, verbose_name='입금 상태'),
        ),
        migrations.RunPython(sync_existing_payment_statuses, migrations.RunPython.noop),
    ]
