# Generated by Django 5.2.17 on 2026-09-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_enrollment_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildeliverylog',
            name='reenrollment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='enrollments.reenrollmentrequest', verbose_name='재수강 신청'),
        ),
        migrations.AddField(
            model_name='reenrollmentrequest',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='신청 시 재수강 기간(일)'),
        ),
        migrations.AddField(
            model_name='reenrollmentrequest',
            name='price_krw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='신청 시 재수강 이용료(원)'),
        ),
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='kind',
            field=models.CharField(choices=[('enrollment_request', '수강 신청 관리자 알림'), ('enrollment_approval', '수강 승인 수강생 알림'), ('enrollment_expiry_7d', '수강 종료 7일 전 알림'), ('account_withdrawal_request', '계정 탈퇴 요청 관리자 알림'), ('reenrollment_request', '재수강 신청 관리자 알림'), ('reenrollment_approval', '재수강 승인 수강생 알림'), ('reenrollment_rejection', '재수강 반려 수강생 알림')], max_length=40, verbose_name='메일 유형'),
        ),
    ]
