# Generated by Django 5.2.17 on 2026-09-27 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_emaildeliverylog_reenrollment_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmed_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='입금 확인 관리자'),
        ),
    ]
