# Generated by Django 5.2.17 on 2026-09-27 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_alter_enrollment_payment_confirmed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AlterField(
            model_name='reenrollmentrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reenrollment_requests', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자'),
        ),
    ]
