# Generated by Django 4.2.30 on 2026-07-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, verbose_name='마지막 시청 위치(초)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='전체 길이(초)')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='진도율')),
                ('is_completed', models.BooleanField(default=False, verbose_name='시청 완료')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='마지막 시청일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progresses', to='enrollments.enrollment', verbose_name='수강')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progresses', to='lessons.lesson', verbose_name='차시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progresses', to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '시청 진도',
                'verbose_name_plural': '시청 진도',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_progress_per_lesson'),
        ),
    ]
