# Generated by Django 4.2.30 on 2026-07-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprogress',
            name='total_watched_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='총 시청 시간(초)'),
        ),
    ]
