# Generated by Django 4.2.30 on 2026-09-17 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_watchprogress_total_watched_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprogress',
            name='last_position_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='재생 위치 기록 시각'),
        ),
        migrations.CreateModel(
            name='ProgressSaveReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_receipts', to='progress.watchprogress')),
            ],
        ),
        migrations.AddConstraint(
            model_name='progresssavereceipt',
            constraint=models.UniqueConstraint(fields=('progress', 'event_id'), name='unique_progress_save_event'),
        ),
    ]
