# Generated by Django 4.2.30 on 2026-07-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerWarningAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_key', models.CharField(max_length=120, verbose_name='경고 키')),
                ('message_hash', models.CharField(max_length=64, verbose_name='메시지 해시')),
                ('message', models.TextField(blank=True, verbose_name='확인한 메시지')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='확인 일시')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_warning_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='확인 관리자')),
            ],
            options={
                'verbose_name': '서버 경고 확인',
                'verbose_name_plural': '서버 경고 확인',
                'ordering': ['-acknowledged_at'],
                'indexes': [models.Index(fields=['warning_key', 'message_hash'], name='core_server_warning_0f0abb_idx'), models.Index(fields=['-acknowledged_at'], name='core_server_acknowl_9172bc_idx')],
                'unique_together': {('warning_key', 'message_hash')},
            },
        ),
    ]
