# Generated by Django 4.2.30 on 2026-07-17 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_price_krw'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='공개일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='courses.course', verbose_name='관련 강의')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='core_notice_is_publ_6abd03_idx'), models.Index(fields=['course', 'is_published', '-published_at'], name='core_notice_course__8a4180_idx')],
            },
        ),
    ]
