# Generated by Django 4.2.30 on 2026-07-07 07:23

import certificates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_certificate_enabled_course_require_quiz_pass_and_more'),
        ('enrollments', '0002_enrollment_completed_at_enrollment_completion_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(default=certificates.models.certificate_number, max_length=40, unique=True, verbose_name='수료증 번호')),
                ('verification_code', models.CharField(default=certificates.models.verification_code, max_length=64, unique=True, verbose_name='검증 코드')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='발급일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='발급 상태')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='PDF 파일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='강의')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment', verbose_name='수강')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '수료증',
                'verbose_name_plural': '수료증',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', 'course'], name='certificate_user_id_2a7ce8_idx'), models.Index(fields=['certificate_no'], name='certificate_certifi_e686f4_idx'), models.Index(fields=['verification_code'], name='certificate_verific_e033f7_idx')],
            },
        ),
    ]
