# Generated by Django 4.2.30 on 2026-07-20 07:57

import certificates.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='기본 수료증 디자인', max_length=100, verbose_name='설정명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('certificate_title', models.CharField(default='수 료 증', max_length=80, verbose_name='수료증 제목')),
                ('issuer_name', models.CharField(default='위드브레인연구소', max_length=120, verbose_name='발급 기관명')),
                ('issuer_subtitle', models.CharField(blank=True, default='WITHBRAIN INSTITUTE', max_length=160, verbose_name='발급 기관 보조 문구')),
                ('representative_name', models.CharField(blank=True, max_length=80, verbose_name='대표자명')),
                ('completion_statement', models.CharField(default='위 사람은 본 교육 과정을 성실히 이수하였음을 증명합니다.', max_length=240, verbose_name='수료 문구')),
                ('logo_image', models.FileField(blank=True, help_text='PNG 또는 JPG 로고를 업로드합니다. 직접 URL로 공개되지 않습니다.', storage=certificates.storage.PrivateCertificateAssetStorage(), upload_to='certificate_assets/logos/', verbose_name='로고 이미지')),
                ('seal_image', models.FileField(blank=True, help_text='투명 배경 PNG 직인을 권장합니다. 직접 URL로 공개되지 않습니다.', storage=certificates.storage.PrivateCertificateAssetStorage(), upload_to='certificate_assets/seals/', verbose_name='직인 이미지')),
                ('accent_color', models.CharField(default='#007B74', max_length=7, verbose_name='포인트 색상')),
                ('footer_note', models.CharField(default='본 수료증은 ONEDU LMS 수료증 검증 페이지에서 진위 여부를 확인할 수 있습니다.', max_length=180, verbose_name='하단 안내 문구')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '수료증 디자인 설정',
                'verbose_name_plural': '수료증 디자인 설정',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
