# Generated by Django 4.2.30 on 2026-07-14 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', '로그인 성공'), ('lesson_view', '차시 화면 진입'), ('video_access', '영상 접근'), ('hls_playlist', 'HLS 재생 시작'), ('attachment_download', '학습 자료 다운로드')], max_length=30, verbose_name='기록 유형')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='브라우저 원문')),
                ('device_summary', models.CharField(blank=True, max_length=160, verbose_name='기기 정보')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='세션 키')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='요청 경로')),
                ('course_id_value', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='강의 ID')),
                ('course_title', models.CharField(blank=True, max_length=200, verbose_name='강의명')),
                ('lesson_id_value', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='차시 ID')),
                ('lesson_title', models.CharField(blank=True, max_length=200, verbose_name='차시명')),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, verbose_name='주의 필요')),
                ('suspicious_reason', models.CharField(blank=True, max_length=255, verbose_name='주의 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='기록일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '접속 보안 로그',
                'verbose_name_plural': '접속 보안 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ac_user_id_c848a8_idx'), models.Index(fields=['event_type', '-created_at'], name='accounts_ac_event_t_4743a9_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_ac_ip_addr_b65cb8_idx'), models.Index(fields=['is_suspicious', '-created_at'], name='accounts_ac_is_susp_a33693_idx')],
            },
        ),
    ]
