# Generated by Django 4.2.30 on 2026-07-17 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', '요청 접수'), ('processing', '처리 중'), ('completed', '처리 완료'), ('canceled', '요청 취소')], db_index=True, default='requested', max_length=20, verbose_name='상태')),
                ('reason', models.TextField(blank=True, verbose_name='요청 사유')),
                ('username_snapshot', models.CharField(blank=True, max_length=150, verbose_name='아이디')),
                ('name_snapshot', models.CharField(blank=True, max_length=100, verbose_name='이름')),
                ('email_snapshot', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('phone_snapshot', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='요청일시')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('admin_note', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '계정 탈퇴 요청',
                'verbose_name_plural': '계정 탈퇴 요청',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='accounts_ac_status_540642_idx'), models.Index(fields=['user', '-requested_at'], name='accounts_ac_user_id_a6d18e_idx')],
            },
        ),
    ]
