# Generated by Django 5.2.17 on 2026-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountwithdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='담당 강의의 실적·정산을 조회합니다. 수강생 기능은 유지되며 관리자 권한은 부여되지 않습니다.', verbose_name='강사 권한'),
        ),
    ]
