# Generated by Django 4.2.30 on 2026-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_enabled',
            field=models.BooleanField(default=True, verbose_name='수료증 발급 사용'),
        ),
        migrations.AddField(
            model_name='course',
            name='require_quiz_pass',
            field=models.BooleanField(default=True, verbose_name='시험 합격 필요'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_progress_percent',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='수료 진도 기준(%)'),
        ),
    ]
