# Generated by Django 4.2.30 on 2026-07-12 11:02

from django.db import migrations, models


def set_im_master_seminar_price(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Course.objects.filter(title__icontains='IM 마스터스 세미나').update(pricing_type='paid', price_krw=30000)
    Course.objects.filter(title__icontains="IM Master's Seminar").update(pricing_type='paid', price_krw=30000)


def unset_im_master_seminar_price(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Course.objects.filter(title__icontains='IM 마스터스 세미나').update(pricing_type='free', price_krw=0)
    Course.objects.filter(title__icontains="IM Master's Seminar").update(pricing_type='free', price_krw=0)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_certificate_enabled_course_require_quiz_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_enrollment_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='기본 수강 기간(일)'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_krw',
            field=models.PositiveIntegerField(default=0, verbose_name='참가비(원)'),
        ),
        migrations.AddField(
            model_name='course',
            name='pricing_type',
            field=models.CharField(choices=[('free', '무료'), ('paid', '유료')], default='free', max_length=10, verbose_name='과금 유형'),
        ),
        migrations.RunPython(set_im_master_seminar_price, unset_im_master_seminar_price),
    ]
