# Generated by Django 4.2.30 on 2026-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_default_enrollment_days_course_price_krw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_krw',
            field=models.PositiveIntegerField(default=0, verbose_name='이용료(원)'),
        ),
    ]
