# Generated by Django 4.2.30 on 2026-07-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_course_price_krw'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('invite_only', '초대 전용'), ('private', '비공개')], default='public', help_text='공개는 모든 회원이 볼 수 있고, 초대 전용은 지정한 회원만 목록과 상세를 볼 수 있습니다.', max_length=20, verbose_name='공개 방식'),
        ),
        migrations.CreateModel(
            name='CourseInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='초대일시')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='courses.course', verbose_name='강의')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대한 관리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대 회원')),
            ],
            options={
                'verbose_name': '강의 초대 회원',
                'verbose_name_plural': '강의 초대 회원',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'active'], name='courses_cou_course__1b068a_idx'), models.Index(fields=['user', 'active'], name='courses_cou_user_id_aa5ab1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='courseinvitation',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_invitation_per_user'),
        ),
    ]
