# Generated by Django 5.2.17 on 2026-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_visibility_courseinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reenrollment_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='재수강 이용료와 함께 설정해 주세요. 미설정 시 운영자가 기간을 배정합니다.', null=True, verbose_name='재수강 기간(일)'),
        ),
        migrations.AddField(
            model_name='course',
            name='reenrollment_price_krw',
            field=models.PositiveIntegerField(blank=True, help_text='유료 강의 재수강 비용입니다. 0원은 무료 연장, 비워 두면 운영자 문의로 안내합니다.', null=True, verbose_name='재수강 이용료(원)'),
        ),
    ]
