# Generated by Django 5.2.17 on 2026-10-03 14:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_alter_course_created_by_and_more'),
        ('enrollments', '0011_alter_enrollment_approved_by_and_more'),
        ('lessons', '0009_lessonattachmentdownload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, help_text='할인 등을 반영한 실제 입금액입니다. 기존 강의 가격으로 추정하지 마세요. 면제는 0원입니다.', null=True, verbose_name='실제 입금액(원)')),
                ('received_on', models.DateField(blank=True, null=True, verbose_name='입금 확인일')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='금액 확인·계산일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('note', models.TextField(blank=True, verbose_name='입금 확인 근거·메모')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='강의')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_record', to='enrollments.enrollment', verbose_name='신규 수강 신청')),
                ('posted_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='금액 확인자')),
                ('renewal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_record', to='enrollments.reenrollmentrequest', verbose_name='재수강 신청')),
            ],
            options={
                'verbose_name': '수강료 거래',
                'verbose_name_plural': '수강료 거래',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='환불액(원)')),
                ('refunded_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='환불 확인일')),
                ('reason', models.CharField(max_length=255, verbose_name='환불 사유')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='반영일시')),
                ('posted_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='환불 확인자')),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='instructors.revenuerecord', verbose_name='원거래')),
            ],
            options={
                'verbose_name': '수강료 환불',
                'verbose_name_plural': '수강료 환불',
                'ordering': ['-refunded_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('fixed', '유료 수강 1건당 정액'), ('percent', '실제 입금액의 일정 비율')], default='fixed', max_length=10, verbose_name='지급 방식')),
                ('fixed_amount', models.PositiveIntegerField(default=0, help_text='이 강사에게 지급할 금액입니다. 실제 입금액이 0원이면 발생하지 않습니다.', verbose_name='건당 지급액(원)')),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=100, help_text='비율 방식: 강의 전체 담당은 100%, 차시별 담당은 합의한 배분 비중을 입력하세요.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(100)], verbose_name='강의 수강료 중 배분 비중(%)')),
                ('royalty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='배분 금액 중 강사 지급률(%)')),
                ('applies_to_renewals', models.BooleanField(default=True, verbose_name='재수강에도 적용')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='적용 시작일')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='적용 종료일')),
                ('note', models.TextField(blank=True, verbose_name='운영자 메모')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='강의')),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사')),
                ('lesson', models.ForeignKey(blank=True, help_text='강의 전체를 담당하면 비워 두세요.', null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='담당 차시')),
            ],
            options={
                'verbose_name': '담당 강사·정산 기준',
                'verbose_name_plural': '담당 강사·정산 기준',
                'ordering': ['course__title', 'lesson__order', 'instructor_id', '-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='InstructorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(verbose_name='발생일')),
                ('course_title', models.CharField(max_length=200, verbose_name='강의명')),
                ('lesson_title', models.CharField(max_length=200, verbose_name='담당 범위')),
                ('terms', models.CharField(max_length=255, verbose_name='적용한 정산 기준')),
                ('amount', models.IntegerField(verbose_name='강사료(원)')),
                ('status', models.CharField(choices=[('pending', '정산 대기'), ('confirmed', '정산 확정'), ('paid', '지급 완료')], default='pending', max_length=12, verbose_name='정산 상태')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='정산 확정일시')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='지급 완료 처리일시')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='정산 확정자')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='지급 완료 처리자')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='instructors.refundrecord', verbose_name='환불')),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='instructors.revenuerecord', verbose_name='수강료 거래')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='instructors.teachingassignment', verbose_name='적용 기준')),
            ],
            options={
                'verbose_name': '강사료 정산 내역',
                'verbose_name_plural': '강사료 정산 내역',
                'ordering': ['-occurred_on', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='revenuerecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('enrollment__isnull', False), ('renewal__isnull', True)), models.Q(('enrollment__isnull', True), ('renewal__isnull', False)), _connector='OR'), name='revenue_one_source'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.CheckConstraint(check=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='teaching_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='instructorearning',
            constraint=models.UniqueConstraint(condition=models.Q(('refund__isnull', True)), fields=('assignment', 'revenue'), name='unique_revenue_earning'),
        ),
        migrations.AddConstraint(
            model_name='instructorearning',
            constraint=models.UniqueConstraint(condition=models.Q(('refund__isnull', False)), fields=('assignment', 'refund'), name='unique_refund_earning'),
        ),
    ]
