# Generated by Django 4.2.30 on 2026-07-07 06:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='보기 내용')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '객관식 보기',
                'verbose_name_plural': '객관식 보기',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', '객관식'), ('short_answer', '주관식')], max_length=30, verbose_name='문제 유형')),
                ('text', models.TextField(verbose_name='문제 내용')),
                ('points', models.PositiveSmallIntegerField(default=10, verbose_name='배점')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '문제',
                'verbose_name_plural': '문제',
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='시험 제목')),
                ('description', models.TextField(blank=True, verbose_name='시험 설명')),
                ('pass_score', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='합격 점수')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, verbose_name='재응시 가능 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='강의')),
            ],
            options={
                'verbose_name': '시험',
                'verbose_name_plural': '시험',
                'ordering': ['course', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='점수')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='만점')),
                ('passed', models.BooleanField(default=False, verbose_name='합격 여부')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='응시 횟수')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='응시 시작 시간')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시간')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='enrollments.enrollment', verbose_name='수강')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='시험')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='응시자')),
            ],
            options={
                'verbose_name': '시험 응시',
                'verbose_name_plural': '시험 응시',
                'ordering': ['-submitted_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='주관식 답안')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('earned_points', models.PositiveSmallIntegerField(default=0, verbose_name='획득 점수')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='응시')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='quizzes.question', verbose_name='문제')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='quizzes.answerchoice', verbose_name='선택한 보기')),
            ],
            options={
                'verbose_name': '응시 답안',
                'verbose_name_plural': '응시 답안',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='시험'),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question', verbose_name='문제'),
        ),
        migrations.AddConstraint(
            model_name='quizattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='quizzes_qui_user_id_68ef05_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'passed'], name='quizzes_qui_quiz_id_915692_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='unique_question_order_per_quiz'),
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_choice_order_per_question'),
        ),
    ]
