# Generated by Django 4.2.30 on 2026-07-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='차시명')),
                ('description', models.TextField(blank=True, verbose_name='차시 설명')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='영상 길이(초)')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='강의')),
            ],
            options={
                'verbose_name': '차시',
                'verbose_name_plural': '차시',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_lesson_order_per_course'),
        ),
    ]
