# Generated by Django 4.2.30 on 2026-07-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, upload_to='lesson_videos/', verbose_name='영상 파일'),
        ),
    ]
