# Generated by Django 4.2.30 on 2026-07-07 01:17

from django.db import migrations, models
import lessons.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, storage=lessons.storage.PrivateVideoStorage(), upload_to='lesson_videos/', verbose_name='영상 파일'),
        ),
    ]
