# Generated by Django 4.2.30 on 2026-07-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hls_converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='HLS 변환일시'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_playlist_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='HLS 재생 목록 경로'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hls_ready',
            field=models.BooleanField(default=False, verbose_name='HLS 준비 완료'),
        ),
    ]
