# Generated by Django 4.2.30 on 2026-07-11 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_lesson_hls_converted_at_lesson_hls_playlist_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLSConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('running', '변환 중'), ('succeeded', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('force', models.BooleanField(default=False, verbose_name='기존 HLS 덮어쓰기')),
                ('transcode', models.BooleanField(default=False, verbose_name='H.264/AAC 재인코딩')),
                ('hls_time', models.PositiveIntegerField(default=6, verbose_name='세그먼트 길이(초)')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='작업 큐 ID')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일시')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hls_jobs', to='lessons.lesson', verbose_name='차시')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hls_conversion_jobs', to=settings.AUTH_USER_MODEL, verbose_name='요청 관리자')),
            ],
            options={
                'verbose_name': 'HLS 변환 작업',
                'verbose_name_plural': 'HLS 변환 작업',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
