# Generated by Django 4.2.30 on 2026-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_hlsconversionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlsconversionjob',
            name='progress_current_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='현재 변환 위치(초)'),
        ),
        migrations.AddField(
            model_name='hlsconversionjob',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='진행률(%)'),
        ),
        migrations.AddField(
            model_name='hlsconversionjob',
            name='progress_total_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='전체 영상 길이(초)'),
        ),
    ]
