# Generated by Django 4.2.30 on 2026-07-11 19:53

from django.db import migrations, models
import django.db.models.deletion
import lessons.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_backfill_lesson_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='자료명')),
                ('file', models.FileField(storage=lessons.storage.PrivateVideoStorage(), upload_to='lesson_attachments/', verbose_name='자료 파일')),
                ('description', models.TextField(blank=True, verbose_name='자료 설명')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lessons.lesson', verbose_name='차시')),
            ],
            options={
                'verbose_name': '학습 자료',
                'verbose_name_plural': '학습 자료',
                'ordering': ['lesson', 'order', 'id'],
            },
        ),
    ]
