# Generated by Django 4.2.30 on 2026-07-15 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_course_price_krw'),
        ('lessons', '0008_lessonattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachmentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_title', models.CharField(blank=True, max_length=200, verbose_name='자료명')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='파일명')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='브라우저 원문')),
                ('device_summary', models.CharField(blank=True, max_length=160, verbose_name='기기 정보')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='다운로드 일시')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='lessons.lessonattachment', verbose_name='학습 자료')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_download_logs', to='courses.course', verbose_name='강의')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_download_logs', to='lessons.lesson', verbose_name='차시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_attachment_downloads', to=settings.AUTH_USER_MODEL, verbose_name='수강생')),
            ],
            options={
                'verbose_name': '학습 자료 다운로드 이력',
                'verbose_name_plural': '학습 자료 다운로드 이력',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['user', '-downloaded_at'], name='lessons_les_user_id_79d7c7_idx'), models.Index(fields=['attachment', '-downloaded_at'], name='lessons_les_attachm_2870e5_idx'), models.Index(fields=['course', '-downloaded_at'], name='lessons_les_course__faa73e_idx'), models.Index(fields=['ip_address', '-downloaded_at'], name='lessons_les_ip_addr_a8af3a_idx')],
            },
        ),
    ]
